export const ACCOMODATIONTYPES = ['Hotel', 'Luxury Hotel', 'Standard']
export const CURRENCIES = [
  {
    id: 'c1e8a6a5-1',
    currency: 'USD',
    name: 'United States Dollar',
  },
  { id: 'c1e8a6a5-2', currency: 'EUR', name: 'Euro', exchangeRate: 11.2 },
  {
    id: 'c1e8a6a5-3',
    currency: 'JPY',
    name: 'Japanese Yen',
  },
  {
    id: 'c1e8a6a5-4',
    currency: 'GBP',
    name: 'British Pound Sterling',
  },
  {
    id: 'c1e8a6a5-5',
    currency: 'AUD',
    name: 'Australian Dollar',
  },
  {
    id: 'c1e8a6a5-6',
    currency: 'CAD',
    name: 'Canadian Dollar',
  },
  {
    id: 'c1e8a6a5-7',
    currency: 'CHF',
    name: 'Swiss Franc',
  },
  {
    id: 'c1e8a6a5-8',
    currency: 'CNY',
    name: 'Chinese Yuan Renminbi',
  },
  {
    id: 'c1e8a6a5-9',
    currency: 'HKD',
    name: 'Hong Kong Dollar',
  },
  {
    id: 'c1e8a6a5-10',
    currency: 'INR',
    name: 'Indian Rupee',
  },
]

export const EXCHANGE_RATES = {
  USD: 10.5,
  EUR: 11.2,
  JPY: 0.075,
  GBP: 13.0,
  AUD: 7.8,
  CAD: 8.1,
  CHF: 11.5,
  CNY: 1.5,
  HKD: 1.35,
  INR: 0.13,
}

export const COUNTRY_NAMES = [
  'Argentina',
  'Australia',
  'Austria',
  'Bangladesh',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Czech Republic',
  'Denmark',
  'Egypt',
  'Estonia',
  'Fiji',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hong Kong, China',
  'India',
  'Indonesia',
  'Ireland',
  'Iceland',
  'Israel',
  'Italy',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Korea',
  'Lithuania',
  'Latvia',
  'Macau, China',
  'Malaysia',
  'Maldives',
  'Mexico',
  'Netherlands',
  'New Zealand',
  'Norway',
  'Oman',
  'Panama',
  'Pakistan',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Saudi Arabia',
  'Serbia',
  'Singapore',
  'South Africa',
  'South Korea',
  'Spain (Canarias)',
  'Spain (Baleares)',
  'Spain',
  'Sweden',
  'Switzerland',
  'Taiwan, China',
  'Thailand',
  'Turkey',
  'United Arab Emirates',
  'United States',
  'Great Britain',
  'Great Britain (London)',
  'Vietnam',
]

export const CURRENCIES_OF_COUTRIES = [
  { label: 'Argentine Peso', value: 'ARS' },
  { label: 'Australian Dollar', value: 'AUD' },
  { label: 'Euro', value: 'EUR' }, // Covers Austria, Belgium, Croatia, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Lithuania, Latvia, Netherlands, Portugal, Spain
  { label: 'Bangladeshi Taka', value: 'BDT' },
  { label: 'Brazilian Real', value: 'BRL' },
  { label: 'Bulgarian Lev', value: 'BGN' },
  { label: 'Canadian Dollar', value: 'CAD' },
  { label: 'Chilean Peso', value: 'CLP' },
  { label: 'Chinese Yuan', value: 'CNY' },
  { label: 'Colombian Peso', value: 'COP' },
  { label: 'Costa Rican Colón', value: 'CRC' },
  { label: 'Cuban Peso', value: 'CUP' },
  { label: 'Czech Koruna', value: 'CZK' },
  { label: 'Danish Krone', value: 'DKK' },
  { label: 'Egyptian Pound', value: 'EGP' },
  { label: 'Fijian Dollar', value: 'FJD' },
  { label: 'Hong Kong Dollar', value: 'HKD' },
  { label: 'Indian Rupee', value: 'INR' },
  { label: 'Indonesian Rupiah', value: 'IDR' },
  { label: 'Icelandic Króna', value: 'ISK' },
  { label: 'Israeli New Shekel', value: 'ILS' },
  { label: 'Japanese Yen', value: 'JPY' },
  { label: 'Jordanian Dinar', value: 'JOD' },
  { label: 'Kazakhstani Tenge', value: 'KZT' },
  { label: 'South Korean Won', value: 'KRW' },
  { label: 'Macanese Pataca', value: 'MOP' },
  { label: 'Malaysian Ringgit', value: 'MYR' },
  { label: 'Maldivian Rufiyaa', value: 'MVR' },
  { label: 'Mexican Peso', value: 'MXN' },
  { label: 'New Zealand Dollar', value: 'NZD' },
  { label: 'Norwegian Krone', value: 'NOK' },
  { label: 'Omani Rial', value: 'OMR' },
  { label: 'Panamanian Balboa', value: 'PAB' },
  { label: 'Pakistani Rupee', value: 'PKR' },
  { label: 'Peruvian Sol', value: 'PEN' },
  { label: 'Philippine Peso', value: 'PHP' },
  { label: 'Polish Złoty', value: 'PLN' },
  { label: 'Qatari Riyal', value: 'QAR' },
  { label: 'Romanian Leu', value: 'RON' },
  { label: 'Russian Ruble', value: 'RUB' },
  { label: 'Saudi Riyal', value: 'SAR' },
  { label: 'Serbian Dinar', value: 'RSD' },
  { label: 'Singapore Dollar', value: 'SGD' },
  { label: 'South African Rand', value: 'ZAR' },
  { label: 'Swedish Krona', value: 'SEK' },
  { label: 'Swiss Franc', value: 'CHF' },
  { label: 'New Taiwan Dollar', value: 'TWD' },
  { label: 'Thai Baht', value: 'THB' },
  { label: 'Turkish Lira', value: 'TRY' },
  { label: 'UAE Dirham', value: 'AED' },
  { label: 'United States Dollar', value: 'USD' },
  { label: 'British Pound Sterling', value: 'GBP' },
  { label: 'Vietnamese Dong', value: 'VND' },
]

export const COUNTRY_EMISSIONS = {
  Argentina: 15.3,
  Australia: 35,
  Austria: 10.3,
  Bangladesh: 112.25,
  Belgium: 12.2,
  Brazil: 9.7,
  Bulgaria: 27.65,
  Canada: 9.75,
  Chile: 27.6,
  China: 53.5,
  Colombia: 14.7,
  'Costa Rica': 4.7,
  Croatia: 11.7,
  Cuba: 32.12,
  'Czech Republic': 20.8,
  Denmark: 10.34,
  Egypt: 44.2,
  Estonia: 32.45,
  Fiji: 75.65,
  Finland: 12.23,
  France: 9.74,
  Germany: 13.2,
  Greece: 30.1,
  'Hong Kong, China': 51.5,
  India: 58.9,
  Indonesia: 62.7,
  Ireland: 26.15,
  Iceland: 10.31,
  Israel: 48.62,
  Italy: 14.3,
  Japan: 39,
  Jordan: 68.9,
  Kazakhstan: 73.45,
  Korea: 55.8,
  Lithuania: 21.85,
  Latvia: 20.56,
  'Macau, China': 79.3,
  Malaysia: 61.5,
  Maldives: 152.2,
  Mexico: 19.3,
  Netherlands: 14.8,
  'New Zealand': 10.3,
  Norway: 11.45,
  Oman: 90.3,
  Panama: 23.1,
  Pakistan: 52.25,
  Peru: 16.6,
  Philippines: 54.3,
  Poland: 30.45,
  Portugal: 19,
  Qatar: 86.2,
  Romania: 16.8,
  'Russian Federation': 24.2,
  'Saudi Arabia': 106.4,
  Serbia: 50.76,
  Singapore: 24.5,
  'South Africa': 51.4,
  'South Korea': 45.76,
  'Spain (Canarias)': 45.65,
  'Spain (Baleares)': 32.74,
  Spain: 11.64,
  Sweden: 11.75,
  Switzerland: 10.3,
  'Taiwan, China': 46.6,
  Thailand: 43.4,
  Turkey: 32.1,
  'United Arab Emirates': 63.8,
  'United States': 16.1,
  'Great Britain': 10.4,
  'Great Britain (London)': 11.5,
  Vietnam: 38.5,
}

export const VEHICLE_TYPE_LIST = [
  'Motorbike',
  'Mini',
  'Lower medium',
  'Executive',
  'Luxury car',
  'SUV or Pickup',
  'Multi purpose(MPV)',
  'Small van',
  'Large van',
  'Heavy truck',
]

export const VEHICLE_ECONOMY = {
  Motorbike: 3.5,
  Mini: 4.5,
  'Lower medium': 5.5,
  Executive: 8,
  'Luxury car': 8,
  'SUV or Pickup': 9,
  'Multi purpose(MPV)': 7.5,
  'Small van': 10,
  'Large van': 15,
  'Heavy truck': 36,
}

export const FUEL_TYPE_LIST = [
  'Petrol',
  'Diesel',
  'Electric',
  'Diesel Hybrid',
  'Petrol Hybrid',
  'Electric Hybrid',
]
